# DigitalOcean App Platform Configuration
# This file defines the deployment configuration for the CRM system

spec:
  name: agent-crm
  region: nyc
  
  # Database - PostgreSQL
  databases:
    - name: crm-db
      engine: PG
      version: "15"
      size: basic
      num_nodes: 1
      
  # Main Next.js Application
  services:
    - name: web
      source_dir: /
      github:
        repo: your-username/agent-crm  # Update this with your actual GitHub repo
        branch: main
        deploy_on_push: true
      
      # Build configuration
      build_command: |
        npm ci
        npx prisma generate
        npm run build
        
      # Run configuration  
      run_command: |
        npx prisma migrate deploy
        npm start
        
      # Environment setup
      environment_slug: node-js
      instance_count: 1
      instance_size_slug: basic-xxs
      
      # HTTP configuration
      http_port: 3000
      
      # Health check
      health_check:
        http_path: /api/health
        
      # Environment variables (will be set via DigitalOcean dashboard)
      envs:
        - key: NODE_ENV
          value: production
          
        - key: DATABASE_URL
          scope: RUN_AND_BUILD_TIME
          type: SECRET
          
        - key: NEXTAUTH_SECRET
          scope: RUN_AND_BUILD_TIME  
          type: SECRET
          
        - key: NEXTAUTH_URL
          scope: RUN_AND_BUILD_TIME
          type: SECRET
          
        - key: CLERK_SECRET_KEY
          scope: RUN_AND_BUILD_TIME
          type: SECRET
          
        - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
          scope: RUN_AND_BUILD_TIME
          type: SECRET
          
      # Routes
      routes:
        - path: /
          
  # Static assets (if needed)
  static_sites: []
  
  # Worker processes (if needed for background jobs)
  workers: []