#
# DigitalOcean App Platform Configuration - Agent CRM
# Complete deployment configuration with database and monitoring
#
name: agent-crm
region: nyc1

# PostgreSQL Database Configuration
databases:
  - name: agent-crm-db
    engine: PG
    version: "15"
    size: basic-xxs
    num_nodes: 1
    production: true

# Main Next.js Web Application
services:
  - name: web
    source_dir: /
    github:
      repo: your-github-username/agent-crm
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: npm install &&npm run build
    run_command: npm start
    
    # Runtime configuration
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # Network configuration
    http_port: 3000
    routes:
      - path: /
    
    # Health monitoring
    health_check:
      http_path: /api/health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Environment Variables
    envs:
      # Core Node.js settings
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
        type: GENERAL
      
      # Database connection (auto-injected by DigitalOcean)
      - key: DATABASE_URL
        value: ${agent-crm-db.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      
      # NextAuth.js configuration
      - key: NEXTAUTH_SECRET
        value: 2zW4bfdt9NR5pBwKt21WTRmAMV8sbHcLxbZSH/zzBGg=
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      
      - key: NEXTAUTH_URL
        value: ${APP_URL}
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      
      # Clerk Authentication (UPDATE WITH YOUR ACTUAL KEYS)
      - key: CLERK_SECRET_KEY
        value: sk_test_your_actual_clerk_secret_key_here
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        value: pk_test_your_actual_clerk_publishable_key_here
        scope: RUN_AND_BUILD_TIME
        type: GENERAL
      
      # Clerk URL configuration
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: /sign-in
        scope: RUN_AND_BUILD_TIME
        type: GENERAL
      
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: /sign-up
        scope: RUN_AND_BUILD_TIME
        type: GENERAL
      
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
        value: /dashboard
        scope: RUN_AND_BUILD_TIME
        type: GENERAL
      
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
        value: /dashboard
        scope: RUN_AND_BUILD_TIME
        type: GENERAL

# Database Migration Job (runs before deployment)
jobs:
  - name: db-migrate
    source_dir: /
    github:
      repo: your-github-username/agent-crm
      branch: main
    build_command: npm install
    run_command: npx prisma db push --accept-data-loss
    environment_slug: node-js
    instance_size_slug: basic-xxs
    kind: PRE_DEPLOY
    envs:
      - key: DATABASE_URL
        value: ${agent-crm-db.DATABASE_URL}
        scope: RUN_TIME
        type: SECRET

# Monitoring and Alerts
alerts:
  - rule: CPU_UTILIZATION
    disabled: false
    value: 80
  - rule: MEM_UTILIZATION
    disabled: false
    value: 80
  - rule: RESTART_COUNT
    disabled: false
    value: 5